"""API routes."""

from __future__ import annotations

from datetime import datetime

from fastapi import APIRouter, Depends, Query

from air_platform.config import AppSettings
from air_platform.ingestion.models import MissingStrategy, ProcessingConfig
from air_platform.llm.use_cases import (
    AnswerNLQueryUseCase,
    GenerateDataQualityReportUseCase,
    SummarizeStationHealthUseCase,
)
from air_platform.metrics.models import MetricConfig, MetricQuery
from air_platform.repositories.errors import InMemoryErrorRepository
from air_platform.repositories.metrics_aggregate import InMemoryMetricsAggregateRepository
from air_platform.repositories.processing_status import InMemoryProcessingStatusRepository
from air_platform.service.dependencies import (
    get_dq_report_use_case,
    get_error_repo,
    get_metrics_aggregate_repo,
    get_nl_query_use_case,
    get_processing_service,
    get_processing_status_repo,
    get_settings,
    get_station_summary_use_case,
)
from air_platform.service.orchestrator import StationProcessingService
from air_platform.service.schemas import (
    DQReportRequest,
    DQReportResponse,
    HealthResponse,
    MetricAggregateResponse,
    MetricResponse,
    NLQueryRequest,
    NLQueryResponse,
    ProcessingErrorResponse,
    ProcessingStatusResponse,
    ProcessStationRequest,
    ProcessStationResponse,
    StationSummaryRequest,
    StationSummaryResponse,
)

router = APIRouter()


@router.get("/health", response_model=HealthResponse)
def healthcheck() -> HealthResponse:
    """Simple health endpoint."""

    return HealthResponse()


@router.post("/stations/{station_id}/process", response_model=ProcessStationResponse)
def process_station(
    station_id: str,
    request: ProcessStationRequest | None = None,
    service: StationProcessingService = Depends(get_processing_service),
    settings: AppSettings = Depends(get_settings),
) -> ProcessStationResponse:
    """Process a station, compute metrics, and persist results."""

    payload = request or ProcessStationRequest()
    processing_config = ProcessingConfig(
        station_id=station_id,
        start_time=payload.start_time,
        end_time=payload.end_time,
        resample_frequency=payload.resample_frequency or settings.default_resample_frequency,
        missing_strategy=(
            payload.missing_strategy or MissingStrategy(settings.default_missing_strategy)
        ),
        flatline_window_minutes=(
            payload.flatline_window_minutes
            if payload.flatline_window_minutes is not None
            else settings.default_flatline_window_minutes
        ),
    )
    metric_config = MetricConfig(
        active_rpm_threshold=(
            payload.active_rpm_threshold
            if payload.active_rpm_threshold is not None
            else settings.active_rpm_threshold
        ),
        specific_power_flow_threshold=(
            payload.specific_power_flow_threshold
            if payload.specific_power_flow_threshold is not None
            else settings.specific_power_flow_threshold
        ),
    )
    summary = service.process_station(processing_config, metric_config)
    return ProcessStationResponse.from_summary(summary)


@router.get("/metrics", response_model=list[MetricResponse])
def get_metrics(
    station_id: str | None = Query(default=None),
    device_id: str | None = Query(default=None),
    start_time: datetime | None = Query(default=None),
    end_time: datetime | None = Query(default=None),
    metric_name: str | None = Query(default=None),
    service: StationProcessingService = Depends(get_processing_service),
) -> list[MetricResponse]:
    """Retrieve previously computed metrics with optional filters."""

    query = MetricQuery(
        station_id=station_id,
        device_id=device_id,
        start_time=start_time,
        end_time=end_time,
        metric_name=metric_name,
    )
    return [MetricResponse.from_domain(metric) for metric in service.get_metrics(query)]


# ---------------------------------------------------------------------------
# LLM-powered endpoints
# ---------------------------------------------------------------------------


@router.post("/stations/{station_id}/summary", response_model=StationSummaryResponse)
def station_health_summary(
    station_id: str,
    request: StationSummaryRequest | None = None,
    use_case: SummarizeStationHealthUseCase = Depends(get_station_summary_use_case),
) -> StationSummaryResponse:
    """Return a plain-English health summary for a station based on stored metrics.

    The summary is generated by an LLM using the deterministic metric values
    already computed and stored by POST /stations/{station_id}/process.
    If the LLM is unavailable, structured metrics are still returned.
    """
    payload = request or StationSummaryRequest()
    result = use_case.execute(
        station_id=station_id,
        start_time=payload.start_time,
        end_time=payload.end_time,
    )
    return StationSummaryResponse.from_result(result)


@router.post("/llm/query", response_model=NLQueryResponse)
def natural_language_query(
    request: NLQueryRequest,
    use_case: AnswerNLQueryUseCase = Depends(get_nl_query_use_case),
) -> NLQueryResponse:
    """Parse a plain-English question and return a deterministic metric answer.

    Flow:
    1. The LLM parses the question into a validated structured query.
    2. The application executes the query deterministically.
    3. The LLM (optionally) phrases the numeric result in natural language.

    The LLM never performs the actual computation.
    """
    result = use_case.execute(question=request.question)
    return NLQueryResponse.from_result(result)


@router.post("/stations/{station_id}/quality-report", response_model=DQReportResponse)
def data_quality_report(
    station_id: str,
    request: DQReportRequest | None = None,
    use_case: GenerateDataQualityReportUseCase = Depends(get_dq_report_use_case),
) -> DQReportResponse:
    """Run the ingestion pipeline and return a plain-English data quality report.

    The quality findings are detected deterministically; the LLM only narrates them.
    If the LLM is unavailable, the structured findings are still returned.
    """
    payload = request or DQReportRequest()
    result = use_case.execute(
        station_id=station_id,
        start_time=payload.start_time,
        end_time=payload.end_time,
    )
    return DQReportResponse.from_result(result)


# ---------------------------------------------------------------------------
# Challenge 3 — event-driven stream endpoints
# ---------------------------------------------------------------------------


@router.get(
    "/metrics/stations/{station_id}",
    response_model=list[MetricAggregateResponse],
)
def get_stream_metrics(
    station_id: str,
    device_id: str | None = Query(default=None),
    metric_type: str | None = Query(default=None),
    start_time: datetime | None = Query(default=None),
    end_time: datetime | None = Query(default=None),
    bucket: str | None = Query(default=None, description="'hour' or 'day'"),
    repo: InMemoryMetricsAggregateRepository = Depends(get_metrics_aggregate_repo),
) -> list[MetricAggregateResponse]:
    """Return incremental aggregates from the real-time event stream.

    These are separate from the batch metrics at ``GET /metrics`` — they reflect
    events consumed by the background queue consumer rather than the SQLite pipeline.
    """
    results = repo.query(
        station_id=station_id,
        device_id=device_id,
        metric_type=metric_type,
        start_time=start_time,
        end_time=end_time,
        bucket=bucket,
    )
    return [MetricAggregateResponse.from_domain(a) for a in results]


@router.get("/processing/status", response_model=ProcessingStatusResponse)
def get_processing_status(
    status_repo: InMemoryProcessingStatusRepository = Depends(get_processing_status_repo),
) -> ProcessingStatusResponse:
    """Return the current consumer processing status and counters."""
    return ProcessingStatusResponse.from_domain(status_repo.get_status())


@router.get("/processing/errors", response_model=list[ProcessingErrorResponse])
def get_processing_errors(
    limit: int = Query(default=50, ge=1, le=500),
    error_repo: InMemoryErrorRepository = Depends(get_error_repo),
) -> list[ProcessingErrorResponse]:
    """Return the most recent processing errors (newest last).

    Use ``limit`` to control how many errors are returned (default 50, max 500).
    """
    return [ProcessingErrorResponse.from_domain(e) for e in error_repo.get_recent(limit=limit)]
